image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

install:
  # Upgrade pip, setuptools and wheel
  - ps: python3 -m pip install --upgrade pip setuptools wheel
  # Use `pip install .` instead of `setup.py install`
  - ps: python3 -m pip install .

build: off

test_script:
  # Print Python version for easier debugging
  - ps: python3 --version
  - ps: python3 -m pip install coverage
  - ps: coverage run setup.py test
  # Codecov report
  - ps: python3 -m pip install codecov
  - ps: codecov
