image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  matrix:
    # Different Python versions to run tests with
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  - set PATH=%PATH%;%PYTHON%
  # Upgrade pip, setuptools and wheel
  - ps: python -m pip install --upgrade pip setuptools wheel
  # Use `pip install .` instead of `setup.py install`
  - ps: python -m pip install .

build: off

test_script:
  # Print Python version for easier debugging
  - ps: python --version
  - ps: python -m pip install coverage
  - ps: coverage run setup.py test
  # Codecov report
  - ps: python -m pip install codecov
  - ps: codecov
