task:
  matrix:
    - name: indexing test (Linux)
      container:
        matrix:
          image: python:3.7
          image: python:3.6
          image: python:3.5
          image: python:3.4

    - name: indexing test (Windows)
      windows_container:
        matrix:
          image: python:3.7
          image: python:3.6
          # No Python 3.4 or 3.5 for Windows
      info_script:
        echo %OS%

    - name: indexing test (macOS)
      osx_instance:
        matrix:
          image: mojave-base
          image: high-sierra-base
      container:
        # Use Python 2.7 for now
        image: python:latest

    - name: indexing test (FreeBSD)
      freebsd_instance:
        matrix:
          image: freebsd-12-0-release-amd64
          image: freebsd-11-2-release-amd64
          image: freebsd-11-1-release-amd64
          image: freebsd-10-4-release-amd64
      container:
        # Use Python 2.7 for now
        image: python:latest

  test_indexing_script:
    # Print Python version for easier debugging
    - python --version
    - python -m unittest tests.test_indexing
