linux_test_task:
  container:
    image: python:latest
  test_indexing_script:
    python -m unittest $CIRRUS_WORKING_DIR/tests/test_indexing.py

windows_test_task:
  windows_container:
    image: python:latest
  test_indexing_script:
    python -m unittest tests\test_indexing.py
