environment:
  CODECOV_TOKEN: ENCRYPTED[fe8b1d1fb2cfca1b2949d30a7a702c7bc0e2d36f65ed94928f589fea6483ed90f4b1e93156091d4b8d96a431b0c6f426]

task:
  matrix:
    # Use the default name.
    # GitHub will require pull requests to pass these tests.
    - container:
        matrix:
          image: python:3.7
          image: python:3.6
          image: python:3.5
          image: python:3.4

    - osx_instance:
        matrix:
          image: mojave-base
          image: high-sierra-base
      container:
        # This has Python 2.7
        image: python:latest

      macos_setup_script:
        # Install Python 3
        - brew install python3
        # Try bootstrapping `pip` from the standard library
        - python3 -m ensurepip --default-pip

    - freebsd_instance:
        matrix:
          image: freebsd-12-0-release-amd64
          image: freebsd-11-2-release-amd64
      container:
        # Use Python 2.7 for now
        image: python:latest

      freebsd_setup_script:
        # Install Python 3 (assume yes when asked for confirmation)
        - pkg install -y python3
        # Try bootstrapping `pip` from the standard library
        - python3 -m ensurepip --default-pip

  install_script:
    # Print Python version for easier debugging
    - python3 --version
    # Upgrade pip, setuptools and wheel
    - python3 -m pip install --upgrade pip setuptools wheel
    # Use `pip install .` instead of `setup.py install`
    - python3 -m pip install .

  test_script:
    # Run tests and compute code coverage
    - python3 -m pip install coverage
    - coverage run setup.py test

  codecov_report_script:
    # Codecov report
    - python3 -m pip install codecov
    - codecov
