linux_test_task:
  name: test (Linux)
  container:
    matrix:
      image: python:latest
      image: python:3.7
      image: python:3.6
      image: python:3.5
      image: python:3.4
  test_indexing_script:
    python -m unittest tests.test_indexing

windows_test_task:
  name: test (Windows)
  windows_container:
    matrix:
      image: python:latest
      image: python:3.7
      image: python:3.6
      # No Python 3.4 or 3.5 container for Windows
  test_indexing_script:
    python -m unittest tests.test_indexing

#  macos_test_task:
#    name: test (macOS)
#    osx_instance:
#      image: mojave-base
#    container:
#      matrix:
#        image: python:latest
#        image: python:3.7
#        image: python:3.6
#  #      image: python:3.5
#  #      image: python:3.4
#    test_indexing_script:
#      python -m unittest tests.test_indexing

freebsd_test_task:
  name: test (FreeBSD)
  freebsd_instance:
    image: freebsd-11-2-release-amd64
  container:
    matrix:
      image: python:latest
      image: python:3.7
      image: python:3.6
      image: python:3.5
      image: python:3.4
  test_indexing_script:
    python -m unittest tests.test_indexing
