container:
  image: python:latest

test_task:
  pwd_script:
    pwd
  ls_script:
    ls
  env_script:
    echo $CIRRUS_WORKING_DIR
  test_script:
    python -m unittest $CIRRUS_WORKING_DIR/test_board.py
