task:
  matrix:
    # Use the default name.
    # GitHub will require pull requests to pass these tests.
    - container:
        matrix:
          image: python:3.7
          image: python:3.6
          image: python:3.5
          image: python:3.4

    - windows_container:
        matrix:
          image: python:3.7
          image: python:3.6
          # No Python 3.4 or 3.5 for Windows

    - osx_instance:
        matrix:
          image: mojave-base
          image: high-sierra-base
      container:
        # Python 2.7 is the default
        image: python:latest
      # Install Python 3
      python_script:
        - brew install python3

    - freebsd_instance:
        matrix:
          image: freebsd-12-0-release-amd64
          image: freebsd-11-2-release-amd64
          image: freebsd-11-1-release-amd64
          image: freebsd-10-4-release-amd64
      container:
        # Python 2.7 is the default
        image: python:latest
      # Install Python 3
      python_script:
        pkg install python3

  setup_script:
    # Use `pip install .` instead of `setup.py install`
    - python -m pip install --no-deps .

  test_script:
    # Print Python version for easier debugging
    - python --version
    - python setup.py test
