task:
  environment:
    CODECOV_TOKEN: ENCRYPTED[fe8b1d1fb2cfca1b2949d30a7a702c7bc0e2d36f65ed94928f589fea6483ed90f4b1e93156091d4b8d96a431b0c6f426]

  matrix:
    # Use the default name.
    # GitHub will require pull requests to pass these tests.
    - container:
        matrix:
          image: python:3.7
          image: python:3.6
          image: python:3.5
          image: python:3.4

    - windows_container:
        matrix:
          image: python:3.7
          image: python:3.6
          # No Python 3.4 or 3.5 for Windows

    - osx_instance:
        matrix:
          image: mojave-base
          image: high-sierra-base
      container:
        # Use Python 2.7 for now
        image: python:latest

    - freebsd_instance:
        matrix:
          image: freebsd-12-0-release-amd64
          image: freebsd-11-2-release-amd64
          image: freebsd-11-1-release-amd64
          image: freebsd-10-4-release-amd64
      container:
        # Use Python 2.7 for now
        image: python:latest

  setup_script:
    # Use `pip install .` instead of `setup.py install`
    - python -m pip install .

  test_script:
    # Print Python version for easier debugging
    - python --version
    - coverage run setup.py test

  codecov_report_script:
    - codecov --token=CODECOV_TOKEN
