language: python

matrix:
  include:
    # Different Ubuntu images and Python versions to run tests with
    # Enumerate all possible combinations, because the other option doesn't seem to work
    - os: linux
      dist: xenial
      python: "3.7"
      # No Python 3.7 archives for Trusty or Precise
      # See https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
    - os: linux
      dist: xenial
      python: "3.6"
    - os: linux
      dist: trusty
      python: "3.6"
    - os: linux
      dist: precise
      python: "3.6"
    - os: linux
      dist: xenial
      python: "3.5"
    - os: linux
      dist: trusty
      python: "3.5"
    - os: linux
      dist: precise
      python: "3.5"
    - os: linux
      dist: xenial
      python: "3.4"
    - os: linux
      dist: trusty
      python: "3.4"
    - os: linux
      dist: precise
      python: "3.4"
    # To add macOS here, see https://docs.travis-ci.com/user/multi-os/#python-example-unsupported-languages

install:
  # Print the Python version for easier debugging
  - python --version
  # Upgrade pip, and setuptools
  - python -m pip install --user --upgrade pip setuptools
  # Use `pip install .` instead of `setup.py install`
  - python -m pip install --user .

script:
  # Run the PEP8 code style checks
  - python -m pip install --user flake8
  - flake8 --filename=*.py --exclude=venv,.eggs .
  # Run tests and compute code coverage
  - python -m pip install --user coverage
  - coverage run setup.py test
  # Codecov report
  - python -m pip install --user codecov
  - codecov
