language: python

matrix:
  include:
    # Different Ubuntu images and Python versions to run tests with
    # Enumerate all possible combinations, because the other option doesn't seem to work
    - os: linux
      dist: xenial
      python: "3.8"
  # Only wait for required builds to finish
  fast_finish: true

env:
  - TOX_PARALLEL_NO_SPINNER="1"

install:
  # Install the latest available Tox
  - python -m pip install --upgrade 'tox>=3.0.0'

script:
  # Run continuous integration steps using Tox
  - tox -v --parallel auto --parallel-live
