image:
  # Different Windows images to run tests with
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  matrix:
    # Different Python versions to run tests with
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python34"
    # Codecov token not needed for AppVeyor

install:
  # Put the Python executable on `PATH`
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  # Print the Python version for easier debugging
  - python --version
  # Upgrade pip, and setuptools
  - python -m pip install --user --upgrade pip setuptools
  # Use `pip install .` instead of `setup.py install`
  - python -m pip install --user .
  # Debug line
  - python -m site --user-base
  # No need to further modify the PATH environment variable

build: off

test_script:
  # Run the PEP8 code style checks
  - python -m pip install --user flake8
  - flake8 --filename=*.py --exclude=venv,.eggs .
  # Run tests and compute code coverage
  - python -m pip install --user coverage
  - coverage run setup.py test
  # Codecov report
  - python -m pip install --user codecov
  - codecov
