image:
  # Different Windows images to run tests with
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  matrix:
    # Different Python versions to run tests with
    - PYTHON: "C:\\Python38-x64"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python34"
    # Codecov token not needed for AppVeyor

matrix:
  exclude:
    # No Python 3.8 on Visual Studio 2013
    - image: Visual Studio 2013
      PYTHON: "C:\\Python38-x64"
    - image: Visual Studio 2013
      PYTHON: "C:\\Python38"
    # Exclude Visual Studio 2017, Python 3.4 configuration from build matrix
    # See pzahemszky/pZudoku#89
    - image: Visual Studio 2017
      PYTHON: "C:\\Python34-x64"
    - image: Visual Studio 2017
      PYTHON: "C:\\Python34"

install:
  # Put the Python executable on `PATH`
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  # Print the Python version for easier debugging
  - python --version
  # Upgrade pip, and setuptools
  - python -m pip install --upgrade pip setuptools
  # Use `pip install .` instead of `setup.py install`
  - python -m pip install .

build: off

test_script:
  # Run the PEP8 code style checks
  - python -m pip install flake8
  - flake8 --filename=*.py --ignore= --exclude=venv,.eggs .
  # Run tests and compute code coverage
  - python -m pip install coverage
  - coverage run setup.py test
  # Codecov report
  - python -m pip install codecov
  - codecov
